name: release
on: workflow_dispatch

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7

      - uses: touchlab/read-property@0.1
        id: version-name
        with:
          file: ./gradle.properties
          property: VERSION_NAME

      - name: Echo Version
        run: echo "${{ steps.version-name.outputs.propVal }}"

      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish Artifacts to Maven Central
        run: ./gradlew publish --no-daemon --stacktrace --no-build-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}

      - name: Create Release
        if: ${{ contains(steps.version-name.outputs.propVal, 'SNAPSHOT') == false }}
        uses: touchlab/release-action@v1.10.0
        with:
          tag: ${{ steps.version-name.outputs.propVal }}

env:
  GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
